###
GET  http://localhost:8082/api/chat/history/UDID-0001
Content-Type: application/json

###
GET  http://localhost:8082/api/users/session
Content-Type: application/json
Authorization: test-secret

###
POST  http://localhost:8082/api/chat/msg
Content-Type: application/json

{
  "session_id": "67347mRRMHaouxoO",
  "user_prompt": "Who are you?"
}


/// API REQUESTS ///

// USERS
// create user invite
###
GET  http://localhost:8082/api/users/invite
Content-Type: application/json
Authorization: 45df515194bfab778db59c9d9e4a47a07ddb81495358684e7bf4b92f4c271d01fe4b7d64f6d74fb58ce1e774cbedc9452da6fdca92e38e97be5292e9b8a06c78

// register invited user
###
POST  http://localhost:8082/api/users/register/invite
Content-Type: application/json

{
  "username": "marconi",
  "password": "mia_rea",
  "invite_token": "5dadfa35a9ce6c1ff9673838b1f0394aca2c7d0077a2e398365c4bb9c9bf08005fa290d7a03aa5eb10563538f9651f51bf88f80680ce60a2696bd8451ed48ff1"
}

// register user
###
POST  http://localhost:8082/api/users/register
Content-Type: application/json

{
  "username": "SuperAdmin",
  "password": "admin_admin"
}

// user login
###
POST  http://localhost:8082/api/users/login
Content-Type: application/json

{
  "username": "SuperAdmin",
  "password": "admin_admin"
}


// get users
###
GET  http://localhost:8082/api/users/
Content-Type: application/json


// AVATARS
//
// get user avatar
###
GET  http://localhost:8082/api/users/1/avatars
Content-Type: application/json
Authorization: tmp_token_superadmin_123


//save avatar
###
POST  http://localhost:8082/api/avatars/save
Content-Type: application/json
Authorization: tmp_token_superadmin_123

{
  "avatar_id": 10,
  "avatar_llm_id": 1,
  "avatar_name": "My New Avatar",
  "avatar_primer": "You are a helpful AI assistant."
}

// get avatar agents
###
GET  http://localhost:8082/api/avatars/10/agents
Content-Type: application/json
Authorization: tmp_token_superadmin_123

// save avatar agent
###
POST http://localhost:8082/api/avatars/agents/save
Content-Type: application/json
Authorization: tmp_token_superadmin_123

{
  "avatar_id": 10,
  "agent_id": 1,
  "llm_id": 1,
  "primer": "Some Primer",
  "is_active": true
}


// AGENTS
//
// get agents
###
GET  http://localhost:8082/api/agents
Content-Type: application/json
Authorization: tmp_token_superadmin_123

// TOOLS
//
// get tools
###
GET  http://localhost:8082/api/tools
Content-Type: application/json
Authorization: tmp_token_superadmin_123


// PLUGINS
//
// get plugins
###
GET  http://localhost:8082/api/plugins
Content-Type: application/json
Authorization: tmp_token_superadmin_123


// LLMS
//
// get llms
###
GET  http://localhost:8082/api/llms
Content-Type: application/json
Authorization: tmp_token_superadmin_123